import React from 'react';
import SectionPrivacy from '../molecules/SectionPrivacy';
import HeadingPrivacy from '../atoms/HeadingPrivacy';
import TextPrivacy from '../atoms/TextPrivacy';
import ListDecimal from '../atoms/ListDecimal';

const ThePrivacyPolicy: React.FC = () => (
  <>
    <SectionPrivacy>
      <HeadingPrivacy>プライバシーポリシー</HeadingPrivacy>
      <TextPrivacy>
        本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。
      </TextPrivacy>
    </SectionPrivacy>
    <SectionPrivacy>
      <HeadingPrivacy>第1条（個人情報）</HeadingPrivacy>
      <TextPrivacy>
        「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報及び容貌、指紋、声紋にかかるデータ、及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指す。
      </TextPrivacy>
    </SectionPrivacy>
    <SectionPrivacy>
      <HeadingPrivacy>第2条（個人情報の収集方法）</HeadingPrivacy>
      <TextPrivacy>
        本ウェブサイトは、ユーザーがお問い合わせフォームからお問い合わせをする際に、氏名、メールアドレス、などの個人情報をお尋ねすることがあります。
      </TextPrivacy>
    </SectionPrivacy>
    <SectionPrivacy>
      <HeadingPrivacy>第3条（個人情報を収集・利用する目的）</HeadingPrivacy>
      <TextPrivacy>本ウェブサイトが個人情報を収集・利用する目的は、以下のとおりです。</TextPrivacy>
      <ListDecimal>
        <li>
          <TextPrivacy>
            ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
          </TextPrivacy>
        </li>
        <li>
          <TextPrivacy>重要なお知らせなど必要に応じたご連絡のため</TextPrivacy>
        </li>
        <li>
          <TextPrivacy>上記の用目的に付随する目的</TextPrivacy>
        </li>
      </ListDecimal>
    </SectionPrivacy>
    <SectionPrivacy>
      <HeadingPrivacy>第4条（利用目的の変更）</HeadingPrivacy>
      <TextPrivacy>
        本ウェブサイトは、利用目的が変更前と関連性を有すると合理的に認められる場合に限り、個人情報の利用目的を変更するものとします。
      </TextPrivacy>
      <TextPrivacy>
        利用目的の変更を行った場合には、変更後の目的について、本ウェブサイト所定の方法により、ユーザーに通知し、または本ウェブサイト上に公表するものとします。
      </TextPrivacy>
    </SectionPrivacy>
    <SectionPrivacy>
      <HeadingPrivacy>第5条（個人情報の第三者提供）</HeadingPrivacy>
      <ListDecimal>
        <li>
          <TextPrivacy>
            本ウェブサイトは、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。
          </TextPrivacy>
          <ListDecimal>
            <li>
              <TextPrivacy>
                人の生命、身体または財産の保護のために必要がある場合であって、本人の同意得ることが困難であるとき
              </TextPrivacy>
            </li>
            <li>
              <TextPrivacy>
                公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき
              </TextPrivacy>
            </li>
            <li>
              <TextPrivacy>
                国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
              </TextPrivacy>
            </li>
            <li>
              <TextPrivacy>
                予め次の事項を告知あるいは公表し、かつ本ウェブサイトが個人情報保護委員会に届出をしたとき
              </TextPrivacy>
              <ListDecimal>
                <li>
                  <TextPrivacy>利用目的に第三者への提供を含むこと</TextPrivacy>
                </li>
                <li>
                  <TextPrivacy>第三者に提供されるデータの項目</TextPrivacy>
                </li>
                <li>
                  <TextPrivacy>第三者への提供の手段または方法</TextPrivacy>
                </li>
                <li>
                  <TextPrivacy>
                    本人の求めに応じて個人情報の第三者への提供を停止すること
                  </TextPrivacy>
                </li>
                <li>
                  <TextPrivacy>本人の求めを受け付ける方法</TextPrivacy>
                </li>
              </ListDecimal>
            </li>
          </ListDecimal>
        </li>
        <li>
          <TextPrivacy>
            前項の定めにかかわらず、次に掲げる場合には、当該情報の提供先は第三者に該当しないものとします。
          </TextPrivacy>
          <ListDecimal>
            <li>
              <TextPrivacy>
                本ウェブサイトが利用目的の達成に必要な範囲内にいて個人情報の取扱いの全部または一部を委託する場合
              </TextPrivacy>
            </li>
            <li>
              <TextPrivacy>
                合併その他の事由による事業の承継に伴って個人情報が提供される場合
              </TextPrivacy>
            </li>
            <li>
              <TextPrivacy>
                個人情報を特定の者との間で共同して利用する場合であって、その旨並びに共同して利用される個人情報の項目、共同して利用する者の範囲、利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について、あらかじめ本人に通知し、または本人が容易に知り得る状態に置いた場合
              </TextPrivacy>
            </li>
          </ListDecimal>
        </li>
      </ListDecimal>
    </SectionPrivacy>
    <SectionPrivacy>
      <HeadingPrivacy>第6条（個人情報の開示）</HeadingPrivacy>
      <ListDecimal>
        <li>
          <TextPrivacy>
            本ウェブサイトは、本人から個人情報の開示を求められたときは、本人に対し、遅滞なくこれを開示します。ただし、開示することにより次のいずれかに該当する場合は、その全部または一部を開示しないこともあり、開示しない決定をした場合には、その旨を遅滞なく通知します。
          </TextPrivacy>
          <ListDecimal>
            <li>
              <TextPrivacy>
                本人または第三者の生命、身体、財産その他の権利利益を害するおそれがある場合
              </TextPrivacy>
            </li>
            <li>
              <TextPrivacy>
                本ウェブサイトの業務の適正な実施に著しい支障を及ぼすおそれがある場合
              </TextPrivacy>
            </li>
            <li>
              <TextPrivacy>その他法令に違反することとなる場合</TextPrivacy>
            </li>
          </ListDecimal>
        </li>
        <li>
          <TextPrivacy>
            前項の定めにかかわらず、履歴情報および特性情報などの個人情報以外の情報については、原則として開示いたしません。
          </TextPrivacy>
        </li>
      </ListDecimal>
    </SectionPrivacy>
    <SectionPrivacy>
      <HeadingPrivacy>第7条（プライバシーポリシーの変更）</HeadingPrivacy>
      <ListDecimal>
        <li>
          <TextPrivacy>
            本ポリシーの内容は、法令その他本ポリシーに別段の定めのある事項を除いて、ユーザーに通知することなく、変更することができるものとします。
          </TextPrivacy>
        </li>
        <li>
          <TextPrivacy>
            本ウェブサイトが別途定める場合を除いて、変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとします。
          </TextPrivacy>
        </li>
      </ListDecimal>
    </SectionPrivacy>
  </>
);

export default ThePrivacyPolicy;
